const {
    deleteInvestigationThinkingResolver,
    updateInvestigationThinkingResolver,
    createInvestigationThinkingResolver,
    updateInvestigationTeamResolver,
    updateInvestigationStatusResolver,
    setChapterIconResolver,
    setInvestigationIconResolver,
    deleteChapterRelatedEntitiesResolver,
    deleteChapterRelatedEntityResolver,
    deleteUpdateChapterRelatedEntitiesResolver,
    updateChapterRelatedEntitiesResolver,
    updateChapterRelatedEntityResolver,
    createChapterRelatedEntitiesResolver,
    createChapterRelatedEntityResolver,
    deleteInvestigationRelatedEntitiesResolver,
    deleteInvestigationRelatedEntityResolver,
    deleteUpdateInvestigationRelatedEntitiesResolver,
    updateInvestigationRelatedEntitiesResolver,
    updateInvestigationRelatedEntityResolver,
    createInvestigationRelatedEntitiesResolver,
    createInvestigationRelatedEntityResolver,
    deleteInvestigationChapterResolver,
    updateInvestigationChapterResolver,
    createInvestigationChaptersResolver,
    createInvestigationChapterResolver,
    deleteInvestigationGraphResolver,
    updateInvestigationGraphResolver,
    createInvestigationGraphResolver,
    deleteInvestigationResolver,
    updateInvestigationResolver,
    createInvestigationOrderableResolver
} = require("../resolvers/investigationResolver")

module.exports = {
    InvestigationMutationType: {
        createInvestigation: createInvestigationOrderableResolver,
        updateInvestigation: updateInvestigationResolver,
        deleteInvestigation: deleteInvestigationResolver,
        createInvestigationGraph: createInvestigationGraphResolver,
        updateInvestigationGraph: updateInvestigationGraphResolver,
        deleteInvestigationGraph: deleteInvestigationGraphResolver,
        createInvestigationChapter: createInvestigationChapterResolver,
        createInvestigationChapters: createInvestigationChaptersResolver,
        updateInvestigationChapter: updateInvestigationChapterResolver,
        deleteInvestigationChapter: deleteInvestigationChapterResolver,
        createInvestigationRelatedEntity: createInvestigationRelatedEntityResolver,
        createInvestigationRelatedEntities: createInvestigationRelatedEntitiesResolver,
        updateInvestigationRelatedEntity: updateInvestigationRelatedEntityResolver,
        updateInvestigationRelatedEntities: updateInvestigationRelatedEntitiesResolver,
        deleteUpdateInvestigationRelatedEntities: deleteUpdateInvestigationRelatedEntitiesResolver,
        deleteInvestigationRelatedEntity: deleteInvestigationRelatedEntityResolver,
        deleteInvestigationRelatedEntities: deleteInvestigationRelatedEntitiesResolver,
        createChapterRelatedEntity: createChapterRelatedEntityResolver,
        createChapterRelatedEntities: createChapterRelatedEntitiesResolver,
        updateChapterRelatedEntity: updateChapterRelatedEntityResolver,
        updateChapterRelatedEntities: updateChapterRelatedEntitiesResolver,
        deleteUpdateChapterRelatedEntities: deleteUpdateChapterRelatedEntitiesResolver,
        deleteChapterRelatedEntity: deleteChapterRelatedEntityResolver,
        deleteChapterRelatedEntities: deleteChapterRelatedEntitiesResolver,
        setInvestigationIcon: setInvestigationIconResolver,
        setChapterIcon: setChapterIconResolver,
        updateInvestigationStatus: updateInvestigationStatusResolver,
        updateInvestigationTeam: updateInvestigationTeamResolver,
        createInvestigationThinking: createInvestigationThinkingResolver,
        updateInvestigationThinking: updateInvestigationThinkingResolver,
        deleteInvestigationThinking: deleteInvestigationThinkingResolver
    }
}